substitutions:
  name: kuchnia-yeelight-ceiling
  remote_mac: "FF:11:22:33:44:55"

esphome:
  name: ${name}
  min_version: 2024.10.0

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true

external_components:
  - source: github://syssi/esphome-yeelight-ceiling-light@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXX"

api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXX"

logger:
  level: DEBUG

# ============================================
# KLUCZOWE: Obsługa BLE pilota YLYK01YL
# ============================================
esp32_ble_tracker:
  setup_priority: -900  # KRYTYCZNE dla jednordzeniowego ESP!
  scan_parameters:
    active: false

xiaomi_ylyk01yl:
  mac_address: ${remote_mac}
  last_button_pressed:
    name: "${name} last button pressed"
  
  # Keycode mapping:
  # 0 = on
  # 1 = off
  # 2 = sun
  # 3 = +
  # 4 = M
  # 5 = -
  
  on_press:
    # Keycode 0 - ON
    - keycode: 0
      then:
        - logger.log: "🔵 Pilot: ON pressed"
        - light.turn_on:
            id: ceiling_light
            brightness: 80%
            color_temperature: 4000 K
    
    # Keycode 1 - OFF
    - keycode: 1
      then:
        - logger.log: "🔴 Pilot: OFF pressed"
        - light.turn_off: ceiling_light
        - light.turn_off: night_light
    
    # Keycode 2 - SUN
    - keycode: 2
      then:
        - logger.log: "☀️ Pilot: SUN pressed"
        - light.turn_on:
            id: ceiling_light
            brightness: 100%
            color_temperature: 2700 K
    
    # Keycode 3 - PLUS
    - keycode: 3
      then:
        - logger.log: "➕ Pilot: + pressed"
        - lambda: |-
            if (id(ceiling_light).current_values.is_on()) {
              auto call = id(ceiling_light).turn_on();
              auto brightness = id(ceiling_light).current_values.get_brightness();
              call.set_brightness(std::min(brightness + 0.1f, 1.0f));
              call.perform();
            } else if (id(night_light).current_values.is_on()) {
              auto call = id(night_light).turn_on();
              auto brightness = id(night_light).current_values.get_brightness();
              call.set_brightness(std::min(brightness + 0.1f, 1.0f));
              call.perform();
            }
    
    # Keycode 4 - M (MOON)
    - keycode: 4
      then:
        - logger.log: "🌙 Pilot: M pressed"
        - if:
            condition:
              light.is_on: night_light
            then:
              - light.turn_off: night_light
              - light.turn_on:
                  id: ceiling_light
                  brightness: 80%
                  color_temperature: 6000 K
            else:
              - light.turn_on:
                  id: night_light
                  brightness: 20%
    
    # Keycode 5 - MINUS
    - keycode: 5
      then:
        - logger.log: "➖ Pilot: - pressed"
        - lambda: |-
            if (id(ceiling_light).current_values.is_on()) {
              auto call = id(ceiling_light).turn_on();
              auto brightness = id(ceiling_light).current_values.get_brightness();
              call.set_brightness(std::max(brightness - 0.1f, 0.05f));
              call.perform();
            } else if (id(night_light).current_values.is_on()) {
              auto call = id(night_light).turn_on();
              auto brightness = id(night_light).current_values.get_brightness();
              call.set_brightness(std::max(brightness - 0.1f, 0.05f));
              call.perform();
            }
  
  on_long_press:
    # Keycode 3 - PLUS LONG
    - keycode: 3
      then:
        - logger.log: "➕ Pilot: + LONG pressed"
        - if:
            condition:
              light.is_on: ceiling_light
            then:
              - light.turn_on:
                  id: ceiling_light
                  brightness: 100%
            else:
              - light.turn_on:
                  id: night_light
                  brightness: 100%
    
    # Keycode 5 - MINUS LONG
    - keycode: 5
      then:
        - logger.log: "➖ Pilot: - LONG pressed"
        - if:
            condition:
              light.is_on: ceiling_light
            then:
              - light.turn_on:
                  id: ceiling_light
                  brightness: 5%
            else:
              - light.turn_on:
                  id: night_light
                  brightness: 5%

# ============================================
# Reszta konfiguracji (bez zmian)
# ============================================
sensor:
  - platform: adc
    pin: GPIO36
    name: "${name} adc1"
    attenuation: 12db
  - platform: adc
    pin: GPIO32
    name: "${name} adc2"
    attenuation: 12db
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 300s
    device_class: "signal_strength"

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO21
    id: output_cold
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO23
    id: output_nightlight
    frequency: 19531Hz

light:
  - platform: monochromatic
    name: "${name}-nightlight"
    id: night_light
    output: output_nightlight
    gamma_correct: 0.7
    on_turn_on:
      - light.turn_off: ceiling_light
  - platform: cwww
    name: "${name}"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    gamma_correct: 0.4
    on_turn_on:
      - light.turn_off: night_light
